"""empty message

Revision ID: 3d1138bbc68
Revises: None
Create Date: 2015-06-12 01:26:23.049064

"""

# revision identifiers, used by Alembic.
revision = '3d1138bbc68'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('display_name', sa.String(length=80), nullable=True),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('user_id', postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_display_name'), 'profile', ['display_name'], unique=True)
    op.create_index(op.f('ix_profile_email'), 'profile', ['email'], unique=True)
    op.create_index(op.f('ix_profile_first_name'), 'profile', ['first_name'], unique=False)
    op.create_index(op.f('ix_profile_last_name'), 'profile', ['last_name'], unique=False)
    op.create_index(op.f('ix_profile_username'), 'profile', ['username'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profile_username'), table_name='profile')
    op.drop_index(op.f('ix_profile_last_name'), table_name='profile')
    op.drop_index(op.f('ix_profile_first_name'), table_name='profile')
    op.drop_index(op.f('ix_profile_email'), table_name='profile')
    op.drop_index(op.f('ix_profile_display_name'), table_name='profile')
    op.drop_table('profile')
    op.drop_table('user')
    ### end Alembic commands ###
