"""empty message

Revision ID: 3ef456aa3c9
Revises: 52b1ca9d63a
Create Date: 2015-06-14 21:53:24.248425

"""

# revision identifiers, used by Alembic.
revision = '3ef456aa3c9'
down_revision = '52b1ca9d63a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('socialmedianetwork',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('network', sa.String(length=10), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('socialmedianetworks',
    sa.Column('socialmedianetwork_id', postgresql.UUID(), nullable=True),
    sa.Column('profile_id', postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.ForeignKeyConstraint(['socialmedianetwork_id'], ['socialmedianetwork.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('socialmedianetworks')
    op.drop_table('socialmedianetwork')
    ### end Alembic commands ###
